# Generated by Django 5.0.7 on 2024-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdshop657', '0002_rename_file_productpage_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='sent_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
